services:
  backend-dev:
    build:
      context: /backend
      dockerfile: /Dockerfile.dev
    profiles: ["dev"]
    image: task-manager-be:1.0.0
    container_name: task-manager-be-dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - backend-net
      - db-net
    depends_on:
      - db
    ports:
       - ${BE_PORT}:${BE_PORT}
       - 9229:9229

  frontend-dev:
    build:
      context: /frontend
      dockerfile: /Dockerfile.dev
    profiles: ["dev"]
    container_name: task-manager-fe-dev
    env_file:
      - ./frontend/.env
    ports:
      - 8080:${FE_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - backend-net
    depends_on:
      - backend-dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    container_name: task-manager-db
    image: postgres:17.5-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /pgdata:/var/lib/postgresql/data
    networks:
      - db-net

# Internal network
networks:
  backend-net:
  db-net:
